---
- name: Update index.html content on web server
  hosts: 192.168.122.34
  become: true
  tasks:
    - name: Update index.html to display "Hello from web server"
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        regexp: '^.*'
        line: 'Hello from web server'
